// Pagefind client, shared by the docs/blog dialog and the site header search.
//
// Pagefind's bundle is generated by `pagefind --site dist/client` after the
// Astro build, so it only exists in production output. In dev the import 404s
// and callers get `null` — surface a hint rather than an error.

export interface PagefindHit {
  url: string
  excerpt: string
  meta: { title?: string }
}

interface PagefindResult {
  id: string
  data: () => Promise<PagefindHit>
}

export interface Pagefind {
  search: (query: string) => Promise<{ results: PagefindResult[] }>
}

let pagefindPromise: Promise<Pagefind | null> | undefined

export function loadPagefind(): Promise<Pagefind | null> {
  // `new Function` hides the import from Vite's static analysis entirely —
  // `/* @vite-ignore */` gets stripped by the TS transform before import
  // analysis runs, so a literal dynamic import fails to resolve in dev.
  pagefindPromise ??= (
    new Function(
      "return import('/pagefind/pagefind.js')",
    )() as Promise<Pagefind>
  ).then(
    (mod) => mod,
    () => null,
  )
  return pagefindPromise
}

/** Top `limit` hits, resolved. Empty when Pagefind is unavailable. */
export async function searchPagefind(
  query: string,
  limit = 8,
): Promise<PagefindHit[]> {
  const pagefind = await loadPagefind()
  if (!pagefind) return []
  const { results } = await pagefind.search(query)
  return Promise.all(results.slice(0, limit).map((result) => result.data()))
}
