// Pagefind's bundle is generated by `pagefind --site dist/client` after the
// Astro build, so it only exists in production output. In dev the import 404s
// and callers get `null`.

export interface PagefindHit {
  url: string;
  excerpt: string;
  meta: { title?: string };
}

interface Pagefind {
  search: (
    query: string,
  ) => Promise<{ results: { id: string; data: () => Promise<PagefindHit> }[] }>;
}

let pagefindPromise: Promise<Pagefind | null> | undefined;

export function loadPagefind(): Promise<Pagefind | null> {
  // A variable specifier keeps Vite from resolving the runtime-only path.
  const url = "/pagefind/pagefind.js";
  pagefindPromise ??= import(/* @vite-ignore */ url).then(
    (mod: Pagefind) => mod,
    () => null,
  );
  return pagefindPromise;
}

/** Top `limit` hits, resolved. Empty when Pagefind is unavailable. */
export async function searchPagefind(
  query: string,
  limit = 8,
): Promise<{ id: string; hit: PagefindHit }[]> {
  const pagefind = await loadPagefind();
  if (!pagefind) return [];
  const { results } = await pagefind.search(query);
  return Promise.all(
    results
      .slice(0, limit)
      .map(async (result) => ({ id: result.id, hit: await result.data() })),
  );
}
